version: "3"
services:

  talktive-server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: talktive-server
    ports:
      - "5050:5050"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  